### ISSUE TITLE
External Broadcast

### ISSUE THREAD

**Issue by tooolbox** [raz-varren/sacrificial-socket#1]
Unless I'm missing something, I don't see a way to just broadcast something on sockets from some other part of my Go code.  Like, perhaps I get a POST request in from some external component, and I want to do a Roomcast based on that.  Can I do that without capturing a socket reference into a global variable or some such?

Thanks.

**Comment by raz-varren** [comment]
You are correct sir! That was not possible before. So now I have added the Broadcast and Roomcast methods to the SocketServer struct. You can now call Broadcast and Roomcast on your SocketServer instance without the need to bring a Socket into global space.

Thanks.

**Comment by tooolbox** [comment]
Thank you!
