### ISSUE TITLE
How to send a message to a single user？

### ISSUE THREAD

**Issue by hel2o** [raz-varren/sacrificial-socket#10]
How to send a message to a single user？

**Comment by raz-varren** [comment]
You can use [Socketcast](https://godoc.org/github.com/raz-varren/sacrificial-socket#Socket.Socketcast) to send messages to individual sockets.

**Comment by hel2o** [comment]
![default](https://user-images.githubusercontent.com/14226648/48453890-3a3c5580-e7f0-11e8-93c1-9dbd7b662e0b.png)
Is that right? But I can't receive the message.
