### ISSUE TITLE
Implement multibackend using Redis server

### ISSUE THREAD

**Issue by susilolab** [raz-varren/sacrificial-socket#2]
is it possible to write implementation for multibackend using redis?
if possible, what correct type to replace mgo.Collection in MMHB struct?
thanks

**Comment by raz-varren** [comment]
Yes, it should be possible to write a multihome backend for Redis. 

In fact I'm so confident that it's possible, that I went ahead and wrote one. You should be able to pull the new backend with `go get github.com/raz-varren/sacrificial-socket...`

There is also a new example of how to use it [here](https://github.com/raz-varren/sacrificial-socket/tree/master/examples/not-so-simple-examples/redis-multihome).

**Comment by susilolab** [comment]
thank you :)
