### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by sidoshi** [raz-varren/sacrificial-socket#3]
Most js packages are downloaded through npm. It would be great if we published the package to npm.

**Comment by raz-varren** [comment]
I have published the client js to npm. Since, I'm not very well versed in using npm for client side js, I would appreciate any constructive critiques of what I've published.

**Comment by sidoshi** [comment]
Instead of setting up the lib on window object, it would be nice if we export it.
So users can import it only where they want to use it.
I can submit a PR if you'd like.

**Comment by sidoshi** [comment]
We also need to set the main file to be `sacrificial-socket.js`.

**Comment by raz-varren** [comment]
A PR would be much appreciated 👍

**Comment by sidoshi** [comment]
Will submit a PR soon!
