### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by nobita0590** [raz-varren/sacrificial-socket#7]
The package should have a config or anything else to enable or disable the log. Now I can stop your package print into the command line. That is fine in development env. but when I go to product. I want to hide all the log

**Comment by raz-varren** [comment]
Sacrificial socket uses my custom [log package](https://github.com/raz-varren/log), which can be configured with different [log levels](https://godoc.org/github.com/raz-varren/log#pkg-constants). 

Here is an example of how to disable logging in sacrificial socket:
```go
package main

import(
	ss "github.com/raz-varren/sacrificial-socket"
	"github.com/raz-varren/log"
	"os"
)

func main() {
        //this will change the log level and where it outputs
	log.SetDefaultLogger(log.NewLogger(os.Stdout, log.LogLevelNone))

        //this will not print any output
	log.Info.Println("log output")

        //this will not print logs either 
	wss := ss.NewServer()
	wss.Shutdown() 

        //this will still log, but will immediately exit the application afterwards
	log.Err.Fatalln("fatal errors will log and exit") 
}
```
This will disable all logging except for fatal errors that would cause the application to exit anyway.

**Comment by raz-varren** [comment]
If you also wanted to stop fatal logs from outputting, you could use ioutil.Discard:
```go
log.SetDefaultLogger(log.NewLogger(ioutil.Discard, log.LogLevelNone))
```

**Comment by nobita0590** [comment]
thankyou. Have a good day for you
