### ISSUE TITLE
is it possible to send message to certain socket id?

### ISSUE THREAD

**Issue by susilolab** [raz-varren/sacrificial-socket#9]
is it possible to send message to certain socket id?. or i have to join to the room?

**Comment by raz-varren** [comment]
It was not possible before, but it was relatively easy to add so I've added [Socketcast](https://godoc.org/github.com/raz-varren/sacrificial-socket#Socket.Socketcast) and published a [new release](https://github.com/raz-varren/sacrificial-socket/releases/tag/1.1.0).
